// <auto-generated />
using System;
using HotelManagementBlazorApp.Info;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementBlazorApp.Migrations
{
    [DbContext(typeof(GuestDb))]
    [Migration("20240312211248_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagementBlazorApp.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GuestId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Guest");

                    b.HasData(
                        new
                        {
                            GuestId = 1,
                            CheckInDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckOutDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateTime(1995, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "SaidulIslam@gmail.com",
                            FirstName = "Saidul",
                            IsCheckedOut = true,
                            LastName = "Islam",
                            PaymentStatus = "Paid",
                            PhoneNumber = "1234567890",
                            RoomTypeId = 2,
                            TotalAmountPaid = 2500m
                        },
                        new
                        {
                            GuestId = 2,
                            CheckInDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckOutDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateTime(1996, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ASMSayem@gmail.com",
                            FirstName = "A.S.M",
                            IsCheckedOut = false,
                            LastName = "Sayem",
                            PaymentStatus = "Paid",
                            PhoneNumber = "1234567890",
                            RoomTypeId = 1,
                            TotalAmountPaid = 1500m
                        },
                        new
                        {
                            GuestId = 3,
                            CheckInDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckOutDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateTime(1995, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "MohammadMaruf@gmail.com",
                            FirstName = "Mohammad",
                            IsCheckedOut = true,
                            LastName = "Maruf",
                            PaymentStatus = "Paid",
                            PhoneNumber = "1234567890",
                            RoomTypeId = 3,
                            TotalAmountPaid = 3500m
                        },
                        new
                        {
                            GuestId = 4,
                            CheckInDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckOutDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateTime(1994, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "AbdullahToha@gmail.com",
                            FirstName = "Abdullah",
                            IsCheckedOut = false,
                            LastName = "Toha",
                            PaymentStatus = "Paid",
                            PhoneNumber = "1234567890",
                            RoomTypeId = 2,
                            TotalAmountPaid = 2500m
                        },
                        new
                        {
                            GuestId = 5,
                            CheckInDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckOutDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateTime(1995, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "MinhajChowdhury@gmail.com",
                            FirstName = "Minhaj",
                            IsCheckedOut = true,
                            LastName = "Chowdhury",
                            PaymentStatus = "Paid",
                            PhoneNumber = "1234567890",
                            RoomTypeId = 3,
                            TotalAmountPaid = 3500m
                        });
                });

            modelBuilder.Entity("HotelManagementBlazorApp.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomType");

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1,
                            PricePerNight = 1500m,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = 2,
                            PricePerNight = 2500m,
                            TypeName = "Premium"
                        },
                        new
                        {
                            RoomTypeId = 3,
                            PricePerNight = 3500m,
                            TypeName = "Deluxe"
                        });
                });

            modelBuilder.Entity("HotelManagementBlazorApp.Models.Guest", b =>
                {
                    b.HasOne("HotelManagementBlazorApp.Models.RoomType", "RoomType")
                        .WithMany("Guests")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManagementBlazorApp.Models.RoomType", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
